/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "如怀",
  "description": "世界上如果有奇迹，那也只是努力的轨迹。",
  "base": "/vuepress/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuepress/vuepress/public/img/bg.jpg"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-cb95862c",
      "path": "/"
    }
  ],
  "themeConfig": {}
}