/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "如怀",
  "description": "web前端技术博客,简洁至上,专注web前端学习与总结",
  "base": "/vuepress/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-cb95862c",
      "path": "/"
    }
  ],
  "themeConfig": {}
}